server.port: 7001

spring:
  application:
    name: kafka

  kafka:
    bootstrap-servers: 127.0.0.1:9092
  graphql:
    enabled: true
    # HTTP POST 요청을 받을 기본 엔드포인트 (기본값은 /graphql)
#    path: /graphql

    # WebSocket으로 구독을 처리할 경로 및 옵션
    websocket:
      # WebSocket 엔드포인트 활성화: path를 지정하면 자동으로 활성화됩니다
      path: /subscribe
      # 클라이언트의 초기 연결 메시지를 기다리는 최대 시간
      connection-init-timeout: 60s
      # 비활성 상태 유지 허용 시간 (기본 backpressure 버퍼 동작)
      idle-timeout: 5m

  datasource:
    url: jdbc:mariadb://localhost:3306/kafka_test?useSSL=false&amp;allowPublicKeyRetrieval=true&amp;serverTimezone=Asia/Seoul
    username: root
    password: 1234qwer!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace #스프링 부트 2.x, hibernate5
  org.springframework.web.socket: DEBUG
  org.springframework.graphql: DEBUG