spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spring3_jpa_example?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root1234!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mustache:
    servlet:
      expose-request-attributes: true  # csrf(auth -> auth.disable()) 을 지운 경우 사용

server:
  servlet:
    session:
      timeout: 1800 # 초기반