version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    hostname: kafka
    environment:
      # KRaft 모드 설정
      KAFKA_BROKER_ID: 1
      CLUSTER_ID: qJPVRgCXToiDvgKIAG4mdw
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      # 외부 클라이언트용 광고 주소 (필요 시 변경)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # 테스트 클러스터에 맞춘 복제 인자
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"  # 클라이언트 연결
      - "9093:9093"  # 내부 controller 용 (외부 노출 필요 없으면 제거)
    volumes:
      - kafka-data:/var/lib/kafka/data
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "5555:5555"
    depends_on:
      - kafka

volumes:
  kafka-data:
    driver: local